---
resources:
- name: tasks
  type: git
  source:
    uri: https://github.com/colinedwardwood/film-production.git
    branch: master

jobs:
- name: ls
  public: true
  plan:
  - get: task
  - task: exec-ls
    file: tasks/pipeline/tasks/ls.yml
