---
resources:
- name: tasks-scripts
  type: git
  source:
    uri: https://github.com/colinedwardwood/film-production.git
    branch: master

jobs:
- name: remove
  public: true
  plan:
  - get: tasks-scripts
  - task: exec-ls
    file: tasks-scripts/pipeline/tasks/remove.yml
