---
resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/colinedwardwood/film-production.git
    #branch: master
    username: woodce@gmail.com
    password: LjPH08n80GH

jobs:
- name: remove
  public: true
  plan:
  - get: scripts
  - task: exec-scripts
    file: scripts/pipeline/tasks/ls.yml
